language: node_js
node_js:
  - "0.12"
deploy:
  provider: heroku
  api_key: 
    secure: 4cecee06-87ac-4f60-bd9f-d24a691f4160
  app: nodeciheroku
  on:
    repo: petrovick/NodeCIHeroku
after_script: 
  - ./node_modules/karma/bin/karma start
  - istanbul cover ./node_modules/mocha/bin/_mocha server/api/**/*.spec.js
  - cat ./coverage/lcov.info ./coverage/karma/**/*.info > lcov.info 
  - node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
